debug: false

site:
    name: Warehouse
    url: /

search:
    index: warehouse

camo: null

paths:
    documentation: data/packagedocs

urls:
    documentation: "https://pythonhosted.org"

logging:
    version: 1
    disable_existing_loggers: false
    formatters:
        default:
            format: '[%(asctime)s %(levelname)s] %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: default
            level: DEBUG
            stream: ext://sys.stdout
    root:
        level: INFO
        handlers: [console]
