version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: "disabled"
  ignore:
  # Always ignore elasticsearch, future versions are always incompatible with our provider
  - dependency-name: "elasticsearch"
  groups:
    # Items in these groups are combined in a single PR
    psycopg:
      patterns:
        # Combine both `psycopg` and `psycopg[c]`
        - "psycopg*"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  groups:
    # Items in these groups are combined in a single PR
    boto3:
      patterns:
        - "boto3*"
    botocore:
      patterns:
        - "botocore*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "daily"
