apiVersion: v1
kind: Secret
metadata:
  name: camo-credentials
  namespace: warehouse-dev
stringData:
  GOCAMO_HMAC: insecurecamokey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camo
  namespace: warehouse-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camo
  template:
    metadata:
      labels:
        app: camo
    spec:
      containers:
        - name: camo
          image: pypa/warehouse-camo:2.0.0
          command:
            - /bin/go-camo
            - --listen=0.0.0.0:9000
            - --header
            - "Access-Control-Allow-Origin: http://warehouse-dev.orb.local"
          envFrom:
            - secretRef:
                name: camo-credentials
          env:
            - name: GOCAMO_MAXSIZE
              value: "10000"
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: camo
  namespace: warehouse-dev
spec:
  selector:
    app: camo
  ports:
    - port: 9000
      targetPort: 9000
