debug: true

site:
    name: Warehouse (dev)

assets:
    directory: "static"

database:
    url: "postgresql://localhost/warehouse"

paths:
    packages: "data/packages"

cache:
    browser:
        simple: 1
        packages: 1
    varnish:
        simple: 120
        packages: 120

fastly: true
