include:
  pyramid_debugtoolbar: True

configurator:
  database:
    url: "postgresql://postgres@db/warehouse"

  download_stats:
    url: "redis://redis:6379/1"

  sessions:
    secret: "an insecure development secret"
    url: "redis://redis:6379/0"

  camo:
    key: "insecure camo key"
    url: "{request.scheme}://{request.domain}:9000/"

  debugtoolbar:
    hosts:
      - 0.0.0.0/0
    panels:
      - pyramid_debugtoolbar.panels.versions.VersionDebugPanel
      - pyramid_debugtoolbar.panels.settings.SettingsDebugPanel
      - pyramid_debugtoolbar.panels.headers.HeaderDebugPanel
      - pyramid_debugtoolbar.panels.request_vars.RequestVarsDebugPanel
      - pyramid_debugtoolbar.panels.renderings.RenderingsDebugPanel
      - pyramid_debugtoolbar.panels.logger.LoggingPanel
      - pyramid_debugtoolbar.panels.performance.PerformanceDebugPanel
      - pyramid_debugtoolbar.panels.routes.RoutesDebugPanel
      - pyramid_debugtoolbar.panels.sqla.SQLADebugPanel
      - pyramid_debugtoolbar.panels.tweens.TweensDebugPanel
      - pyramid_debugtoolbar.panels.introspection.IntrospectionDebugPanel

  pyramid:
    reload_assets: True
    reload_templates: True
    prevent_http_cache: True
