name: Development Environment

on:
  schedule:
    - cron: '0 13 * * *'  # once a day at around 9am eastern
  workflow_dispatch:

jobs:
  build:
    # TODO: Should we test on other platforms like Windows and Mac?
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - run: make build
      - run: docker compose up -d
      - run: docker compose ps
      - run: make initdb
      - run: make tests
